apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: appraisal-config-server-app
spec:
  serviceName: "appraisal-config-server-app"
  replicas: 1
  selector:
    matchLabels:
      app: appraisal-config-server-app
  template:
    metadata:
      labels:
        app: appraisal-config-server-app
    spec:
      containers:
        - name: appraisal-config-server-app
          image: lolalambe/appraisal-config-server:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          env:
            - name: GIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: appraisal-secrets
                  key: GIT_USERNAME
                  optional: false
            - name: GIT_PERSONAL_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: appraisal-secrets
                  key: GIT_PERSONAL_ACCESS_TOKEN
                  optional: false